name: Bug report
description: Report a bug
title: "[Bug]"
labels: ["bug report"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a bug report.
        Please complete the following form to ask us for help with your issue.
  - type: checkboxes
    id: checks
    attributes:
      label: Checked
      description: Please confirm checking the following options.
      options:
        - label: I added a descriptive title
          required: true
        - label: I am using dependency versions in the environment.yaml file
          required: true
  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
  - type: textarea
    id: logs_error_messages
    attributes:
      label: Relevant logs, tracebacks, messages, etc.
      description: Please copy-paste any relevant logs and/or error messages.
      render: shell